# -*- coding: utf-8 -*-
"""DEEP LEARNING.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cEc6OF3dbzfaFom-_DWurWwxrWT9QesH
"""

!pip install openai

import openai
import urllib.request
from PIL import Image
import cv2
from google.colab.patches import cv2_imshow

openai.api_key = "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"

string = '''
One day, a fox became very hungry as he went to search for some food  He searched high and low, but couldn’t find something that he could eat.
Finally, as his stomach rumbled, he stumbled upon a farmer’s wall. At the top of the wall, he saw the biggest, juiciest grapes he’d ever seen.
They had a rich, purple color, telling the fox they were ready to be eaten.
To reach the grapes, the fox had to jump high in the air. As he jumped, he opened his mouth to catch the grapes, but he missed.
 The fox tried again but missed yet again.
He tried a few more times but kept failing.
Finally, the fox decided it was time to give up and go home. While he walked away, he muttered, “I’m sure the grapes were sour anyway.”
'''

words = string.split('.')
print(len(words))

for i in range(0,len(words)):
    if(i > 6):
      break;
    print("Input", words[i])
    img_response = openai.Image.create(prompt = words[i], n=1, size="512x512")
    img_url=img_response['data'][0]['url']
    urllib.request.urlretrieve(img_url, 'image.png')
    img = cv2.imread("image.png")
    cv2_imshow(img)

#using summary of story
import torch

!pip install transformers

from transformers import AutoModelWithLMHead, AutoTokenizer

tokenizer = AutoTokenizer.from_pretrained('t5-base')
model = AutoModelWithLMHead.from_pretrained('t5-base', return_dict=True)

text=('''
    One day, a fox became very hungry as he went to search for some food  He searched high and low, but couldn’t find something that he could eat.
Finally, as his stomach rumbled, he stumbled upon a farmer’s wall. At the top of the wall, he saw the biggest, juiciest grapes he’d ever seen.
They had a rich, purple color, telling the fox they were ready to be eaten.
To reach the grapes, the fox had to jump high in the air. As he jumped, he opened his mouth to catch the grapes, but he missed.
 The fox tried again but missed yet again.
He tried a few more times but kept failing.
Finally, the fox decided it was time to give up and go home. While he walked away, he muttered, “I’m sure the grapes were sour anyway.”


''')

inputs = tokenizer.encode("summarize: " + text, return_tensors='pt', max_length=2000, truncation=True)

summary_ids = model.generate(inputs, max_length=300, min_length=80, length_penalty=5., num_beams=2)

summary = tokenizer.decode(summary_ids[0])

summary

words = summary.split('.')
for i in range(0,len(words)):
    if( i > 6 ):
      break
    print("Input: ", words[i])
    img_response = openai.Image.create(prompt = words[i], n=1, size="512x512")    # 256x256, 512x512, 1024x1024
    img_url=img_response['data'][0]['url']
    urllib.request.urlretrieve(img_url, 'image.png')
    img = cv2.imread("image.png")
    cv2_imshow(img)